apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argo-applicationset
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
  - web:
      url: https://github.com/speedfl/argocd-applicationset-extension.git/ui/dist/extension.tar